language: python
python:
  - "2.7"

install:
  - pip uninstall -y pytest
  - pip install --use-mirrors pytest==$PYTEST_VERSION
  - pip install --pre -i https://devpi.net/hpk/dev/+simple/ -U devpi
  - pip install --use-mirrors simplejson
env:
  - PYTEST_VERSION=2.4.2
script: 
  - python run.py
